### ISSUE TITLE
Question: Will this work through WASM?

### ISSUE THREAD

**Issue by davidnagli** [goto-bus-stop/node-resolve#1]
This might sound crazy... but I’m wondering if it might be worth it to access Rust node-resolve from Node.

Is it even possible to compile such a complex rust project like this one into WASM? Do you have any benchmarks or some ballpark numbers to get an idea of the performance?

**Comment by goto-bus-stop** [comment]
I have no idea about performance honestly! But, it won't immediately work as wasm because this project uses a lot of filesystem calls. In fact, it doesn't do much else 😛 using it in Node would require calling out to JavaScript for filesystem access, which would cost a little bit of time, so I wouldn't expect to see significant improvements (if any)
